// Export helpers — CSV download + a printable summary (Save-as-PDF via the OS
// print dialog, no extra dependency).

function download(filename, text, type = "text/plain") {
  const blob = new Blob([text], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = filename;
  document.body.appendChild(a); a.click(); a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

const esc = v => `"${String(v ?? "").replace(/"/g, '""')}"`;

// Transactions → CSV (spreadsheet / accountant friendly).
export function exportTransactionsCSV(entries = []) {
  const rows = [["date", "type", "amount", "note"].join(",")]
    .concat(entries.map(e => [e.date, e.type, e.amount, e.note || ""].map(esc).join(",")));
  download(`folio-transactions-${new Date().toISOString().slice(0, 10)}.csv`, rows.join("\n"), "text/csv");
}

// Opens a clean, printable financial summary in a new tab and triggers print
// (the user can "Save as PDF"). Returns false if a popup blocker stopped it.
export function openPrintableReport(d) {
  const cur = d.currency || "EUR";
  const money = n => { try { return new Intl.NumberFormat(undefined, { style: "currency", currency: cur, maximumFractionDigits: 0 }).format(n || 0); } catch { return Math.round(n || 0).toString(); } };
  const date = new Date().toLocaleDateString("en-US", { day: "numeric", month: "long", year: "numeric" });
  const row = (l, v) => `<div class=row><span class=lbl>${l}</span><span class=val>${v}</span></div>`;
  const budgetRows = d.budget && d.budget.categories?.length
    ? `<h2>Budget — ${d.budget.month}</h2>` + d.budget.categories.map(c => row(c.label, `${money(c.spent)} / ${money(c.budgeted)}`)).join("")
    : "";
  const txns = (d.entries || []).slice(0, 25)
    .map(e => row(`${e.date} · ${e.type}`, `${e.type === "deposit" ? "+" : "−"}${money(e.amount)}`)).join("") || `<div class=sub>No transactions yet.</div>`;

  const html = `<!doctype html><html><head><meta charset="utf-8"><title>Folio — financial summary</title>
  <style>
    body{font-family:-apple-system,Inter,Segoe UI,system-ui,sans-serif;max-width:680px;margin:40px auto;padding:0 24px;color:#111;}
    h1{font-size:24px;margin:0 0 2px;letter-spacing:-.02em}
    .sub{color:#666;margin-bottom:24px;font-size:13px}
    h2{font-size:12px;text-transform:uppercase;letter-spacing:.08em;color:#999;margin:26px 0 4px}
    .row{display:flex;justify-content:space-between;padding:9px 0;border-bottom:1px solid #eee;font-size:14px}
    .lbl{color:#555}.val{font-weight:700}
    @media print{body{margin:0}}
  </style></head><body>
    <h1>Folio — financial summary</h1>
    <div class=sub>${date}</div>
    <h2>Net worth</h2>
    ${row("Net worth", money(d.netWorth))}
    ${row("Assets", money(d.totalAssets))}
    ${row("Liabilities", money(d.totalLiab))}
    <h2>Cash flow</h2>
    ${row("Monthly income", money(d.income))}
    ${row("Investing / month", money(d.investable))}
    ${row("Total deposited", money(d.totalDep))}
    ${row("Total withdrawn", money(d.totalWith))}
    <h2>Health</h2>
    ${row("Financial health", `${d.healthScore}/100 · ${d.healthLabel || ""}`)}
    ${budgetRows}
    <h2>Recent transactions</h2>
    ${txns}
    <p style="margin-top:30px;color:#aaa;font-size:11px">Generated by Folio · general information, not financial advice</p>
  </body></html>`;

  const w = window.open("", "_blank");
  if (!w) return false;
  w.document.write(html);
  w.document.close();
  setTimeout(() => { w.focus(); w.print(); }, 350);
  return true;
}
